{% set name = "intervals" %}
{% set version = "0.9.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "c49f6956d0f26e4b3b1d07059c3801146747fa1e372c0023b171a53ea3bdfef5" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - infinity >=0.1.3

test:
  imports:
    - intervals

about:
  home: https://github.com/kvesteri/intervals
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: Python tools for handling intervals (ranges of comparable objects).
  dev_url: https://github.com/kvesteri/intervals
  doc_url: https://github.com/kvesteri/intervals

extra:
  recipe-maintainers:
    - pmlandwehr
