{% set name = "intervals" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c7ee568c583ca857c0d91af6d90ee5e0e8adef3f5646d0076bfb87305ae43090

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - infinity >=0.1.3

test:
  imports:
    - intervals
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kvesteri/intervals
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Python tools for handling intervals (ranges of comparable objects).
  dev_url: https://github.com/kvesteri/intervals
  doc_url: https://github.com/kvesteri/intervals

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
